theme: jekyll-theme-architect

navigation:
  - title: Mirela Budăeş
    url: /
    description: Personal Coaching
  - title: How do I work?
    url: /how-do-i-work/
    description: Personal Coaching
